---
title: "Biol 432 Group project-Question 1"
author: "Chenyang Wu"
date: "2022/3/21"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Project Info
#### **Group name**: Teambits
#### **Date**: 2022/3/21
#### **GitHub Link**: https://github.com/carolinetang77/BIOL432-group1



### Research question: Are mutation rates correlated with transmission method? do certain transmission methods have higher mutation rates?

#### Load the packages we will need

```{r message=FALSE, warning=FALSE}
library(dplyr) 
library(ggplot2)
library(BiocManager)
library(genbankr)
library(rentrez)
```

#### Input the data
```{r}
Table1 <- read.csv("./InputData/TableS1.csv")
Table9 <- read.csv("./InputData/TableS9.csv")

readLines("./InputData/TableS8.dat", n = 10)
Table8 <- read.table("./InputData/TableS8_edited.dat", header = F) 

Table11 <- read.csv("./InputData/TableS11.csv")
```


```{r}
# Check how many types of virus in table S9
table(Table9$virus)

# table(Table9$tree)
```

```{r}
# Check the corresponding transmission type to the abbreviation
list(Table1$Abbreviation)
list(Table1$Transmission)
```


#### Combine the relevant columns into 1 table
```{r}
# Label the transmission type to the dataset
dNdSData <- Table9 %>% 
  mutate(Transmission_Type = recode(virus, 
                                    "BCoV1" = "aerosolic", 
                                    "CHIKV" = "vector", 
                                    "DENV" = "vector", 
                                    "Ebola" = "body_fluids", 
                                    "EVA" = "fecal-oral", 
                                    "EVB" = "fecal-oral", 
                                    "EVC" = "fecal-oral",
                                    "EVCr" = "fecal-oral",
                                    "EVD" = "fecal-oral", 
                                    "H3N2" = "aerosolic", 
                                    "HCV" = "blood/sexual",
                                    "HCVr" = "blood/sexual",
                                    "HDV" = "blood/sexual",
                                    "HMPV" = "aerosolic", 
                                    "HRSV" = "aerosolic", 
                                    "HRV3" = "aerosolic", 
                                    "MERS" = "aerosolic",
                                    "MMV" = "aerosolic", 
                                    "MRV" = "aerosolic",
                                    "Norwalk" = "fecal-oral",
                                    "OHVA" = "fecal-oral", 
                                    "PeVA" = "aerosolic",
                                    "RVA" = "aerosolic",
                                    "SARS2" = "aerosolic",   
                                    "SV" = "fecal-oral",
                                    "TBEV" = "vector",
                                    "WNV" = "vector", 
                                    "YFV" = "vector",
                                    "ZIKV" = "vector")) 

# 
ggplot(dNdSData, aes(x = Transmission_Type, 
                      y = meandNdS, 
                      na.rm = TRUE, 
                      fill = Transmission_Type)) + 
  geom_boxplot(alpha = 0.8) +
  theme_bw() + 
  scale_fill_brewer(palette = "Set2") + 
  labs(x = "Transmission Types", y = "Mean dNdS") + 
  ggtitle("Boxplot of MeandNdS among different Transmission Types") 
```

```{r}
MutaRate <- Table8 %>% 
  mutate(Transmission_Type = recode(V1, 
                                    "BCoV1" = "aerosolic", 
                                    "CHIKV" = "vector", 
                                    "DENV" = "vector", 
                                    "Ebola" = "body_fluids", 
                                    "EVA" = "fecal-oral", 
                                    "EVB" = "fecal-oral", 
                                    "EVC" = "fecal-oral",
                                    "EVCr" = "fecal-oral",
                                    "EVD" = "fecal-oral", 
                                    "H3N2" = "aerosolic", 
                                    "HCV" = "blood/sexual",
                                    "HCVr" = "blood/sexual",
                                    "HDV" = "blood/sexual",
                                    "HMPV" = "aerosolic", 
                                    "HRSV" = "aerosolic", 
                                    "HRV3" = "aerosolic", 
                                    "MERS" = "aerosolic",
                                    "MMV" = "aerosolic", 
                                    "MRV" = "aerosolic",
                                    "Norwalk" = "fecal-oral",
                                    "OHVA" = "fecal-oral", 
                                    "PeVA" = "aerosolic",
                                    "RVA" = "aerosolic",
                                    "SARS2" = "aerosolic",   
                                    "SV" = "fecal-oral",
                                    "TBEV" = "vector",
                                    "WNV" = "vector", 
                                    "YFV" = "vector",
                                    "ZIKV" = "vector")) 


ggplot(MutaRate, aes(x = Transmission_Type, 
                      y = V2, 
                      na.rm = TRUE, 
                      fill = Transmission_Type)) + 
  geom_boxplot(alpha = 0.8) +
  theme_bw() + 
  scale_fill_brewer(palette = "Set2") + 
  labs(x = "Transmission Types", y = "Mutation Rate") + 
  ggtitle("Boxplot of MeandNdS among different Transmission Types") 

```


```{r}
table(Table11$virus)
```


```{r}
# Random pick 10 IDs for each virus
set.seed(1)
IDs <- Table11 %>%
  group_by(virus) %>%
  sample_n(10)
```

```{r}
# Double check if the code correctly pick 10 IDs from each virus
table(IDs$virus)

# Create the id list
ncbi_ids <- IDs$ID 

```

```{r, echo = F}
#
Q1ID <- GBAccession(ncbi_ids)
Q1ID
class(Q1ID)
Q1Gbk <- readGenBank(Q1ID)

```

```{r}
# Search the sequence info from ncbi
Q1Vir <- entrez_fetch(db = "nuccore", id = ncbi_ids, rettype = "fasta") 
Q1Seq <- strsplit(Q1Vir, split = "\n\n", fixed = T)
Q1Seq <- unlist(Q1Seq)

header <- gsub("(^>.*genome|*cds|*sequence|*SEQUENCES|*RNA)\\n[ATCG].*", "\\1", Q1Seq)

seq <- gsub("^>.*genome\\n([ATCG].*)", "\\1", Q1Seq)
seq <- gsub("^>.*cds\\n([ATCG].*)", "\\1", seq)
seq <- gsub("^>.*sequence\\n([ATCG].*)", "\\1", seq)
seq <- gsub("^>.*SEQUENCES\\n([ATCG].*)", "\\1", seq)
seq <- gsub("^>.*RNA\\n([ATCG].*)", "\\1", seq)

Q1SeqTable <- data.frame(Name = header, Sequence = seq)
Q1SeqTable$Sequence <- gsub("\n", "", Q1SeqTable$Sequence)

# There are several lines have different ending words, so we will output the data set and adjust it manually.
write.csv(Q1SeqTable, "./InputData/Q1Seq.csv", row.names = F)
```

```{r}
# Input the edited data
Q1Sequence <- read.csv("./InputData/Q1Seq.csv")


```




